"""XDG-compliant configuration and session loading.

The alter-runtime daemon reads its configuration from three sources, in order
of precedence:

1. Environment variables (ALTER_RUNTIME_*)
2. User config file at $XDG_CONFIG_HOME/alter/runtime.yaml (default
   ~/.config/alter/runtime.yaml), dev-only, see the gate at ``DaemonConfig.load``
3. Behaviour toggles the member set from their own CLI, at
   $XDG_CONFIG_HOME/alter/daemon-toggles.json. Booleans on a closed allowlist
   and nothing else, which is why it needs no dev gate.
4. Built-in defaults

The authoritative identity session is written by the separate CLI
into its OS-native secure credential store (DPAPI / macOS
Keychain / libsecret, with an AES-256-GCM encrypted-file
fallback at $XDG_CONFIG_HOME/alter/enc/session.bin keyed by
$XDG_CONFIG_HOME/alter/enc-keyfile). Older installs may still carry the
legacy plaintext $XDG_CONFIG_HOME/alter/session.json. We read the session
through the same store contract the CLI uses but never mutate it - the
daemon does not manage login, never writes any store backend, and never
migrates between backends (that is the CLI's job).

Socket paths:
- Linux:   /run/user/$UID/alter.sock
- macOS:   ~/Library/Application Support/alter/runtime.sock
- Windows: \\\\.\\pipe\\alter-runtime   (Named Pipe, not yet supported)
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

__all__ = [
    "BEHAVIOUR_TOGGLE_FIELDS",
    "ConfigError",
    "DaemonConfig",
    "Session",
    "behaviour_toggles_path",
    "cache_dir",
    "config_dir",
    "data_dir",
    "doctrine_projection_dir",
    "enc_keyfile_path",
    "enc_session_path",
    "keypair_path",
    "load_config",
    "load_session",
    "read_os_secret_store",
    "read_enc_store",
    "runtime_state_dir",
    "state_dir",
    "unix_socket_path",
]


# ---------------------------------------------------------------------------
# XDG helpers
# ---------------------------------------------------------------------------


def _xdg_path(env_var: str, fallback: str) -> Path:
    """Return $env_var if set, else $HOME/fallback."""
    raw = os.environ.get(env_var)
    if raw:
        return Path(raw).expanduser()
    return Path.home() / fallback


def config_dir() -> Path:
    """Return $XDG_CONFIG_HOME/alter (default ~/.config/alter)."""
    return _xdg_path("XDG_CONFIG_HOME", ".config") / "alter"


def cache_dir() -> Path:
    """Return $XDG_CACHE_HOME/alter (default ~/.cache/alter)."""
    return _xdg_path("XDG_CACHE_HOME", ".cache") / "alter"


def state_dir() -> Path:
    """Return $XDG_STATE_HOME/alter (default ~/.local/state/alter)."""
    return _xdg_path("XDG_STATE_HOME", ".local/state") / "alter"


def data_dir() -> Path:
    """Return $XDG_DATA_HOME/alter-runtime (default ~/.local/share/alter-runtime).

    The directory is created on first access with mode ``0o700`` so that the
    ``inbox.jsonl`` cache cannot be world-read. Used by the InboxWriter
    subscriber to persist alter-to-alter messages projected from the per-handle
    DO SSE stream.
    """
    path = _xdg_path("XDG_DATA_HOME", ".local/share") / "alter-runtime"
    path.mkdir(parents=True, exist_ok=True, mode=0o700)
    return path


def runtime_state_dir() -> Path:
    """Return $XDG_STATE_HOME/alter-runtime (default ~/.local/state/alter-runtime).

    Distinct from :func:`state_dir` (which is the broader ``alter`` namespace
    used by the CLI) - the runtime daemon owns its own state subtree so
    that crash-recovery checkpoints (e.g. ``messaging.json``) cannot collide
    with state written by sibling tools. Created on first access with mode
    ``0o700``.
    """
    path = _xdg_path("XDG_STATE_HOME", ".local/state") / "alter-runtime"
    path.mkdir(parents=True, exist_ok=True, mode=0o700)
    return path


def doctrine_projection_dir() -> Path:
    """Return $XDG_DATA_HOME/alter/doctrine (default ~/.local/share/alter/doctrine).

    The canonical home of the local read-only doctrine projection:
    ``personal.jsonl`` / ``collective.jsonl`` plus their per-scope checkpoint
    files live here. Note the ``alter/`` namespace (NOT ``alter-runtime/``):
    the projection is pinned under the broad ``alter`` data tree alongside the
    CLI's other ``alter``-namespaced data, not the daemon's private
    ``alter-runtime`` subtree.

    Created on first access with mode ``0o700`` so the projected doctrine (which
    may carry personal-scope notes) cannot be world-read.
    """
    path = _xdg_path("XDG_DATA_HOME", ".local/share") / "alter" / "doctrine"
    path.mkdir(parents=True, exist_ok=True, mode=0o700)
    return path


def keypair_path() -> Path:
    """Path to the device Ed25519 keypair (generated by `alter-runtime init`)."""
    return config_dir() / "keypair.json"


def unix_socket_path() -> Path:
    """Platform-appropriate local socket path.

    On Linux we prefer $XDG_RUNTIME_DIR (which maps to /run/user/$UID on
    systemd distros), falling back to /tmp. On macOS the socket lives under
    Application Support because /run/user doesn't exist.
    """
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "alter" / "runtime.sock"
    runtime = os.environ.get("XDG_RUNTIME_DIR")
    if runtime:
        return Path(runtime) / "alter.sock"
    # Fallback: per-user socket under /tmp
    uid = os.getuid() if hasattr(os, "getuid") else 0
    return Path(f"/tmp/alter-{uid}.sock")


# ---------------------------------------------------------------------------
# Session (written by the CLI, read-only here)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Session:
    """Snapshot of the CLI session.json file.

    Mirrors the shape the CLI writes on login.
    """

    handle: str
    api: str
    jwt: str
    jwt_expires_at: str
    consent_tier: int
    user_id: str
    email: str
    orgs: list[dict[str, Any]] = field(default_factory=list)
    id_token: str | None = None
    refresh_token: str | None = None
    refresh_expires_at: str | None = None
    logged_in_at: str | None = None
    #: Per-invocation ES256 signing key id. Written by ``alter login`` and
    #: cached here alongside the private half written to
    #: ``~/.config/alter/signing-keys/<kid>.pem`` (or the legacy
    #: ``signing-key.pem``). When present, the daemon builds a compact JWS
    #: ``Mcp-Invocation-Signature`` header for every MCP ``tools/call`` so
    #: the backend's per-invocation signing gate passes.
    signing_kid: str | None = None
    #: SHA-256 (base64url) of the DER-encoded SubjectPublicKeyInfo (SPKI) of
    #: the ES256 signing key. Written by ``alter login`` alongside
    #: ``signing_kid`` (current login format). The daemon uses this to detect a
    #: split-brain where the resolved private key no longer matches what the
    #: session recorded at login time, refusing to sign with the wrong key
    #: rather than emitting a JWS the server will reject as
    #: ``handle_mismatch``.  ``None`` on legacy sessions (legacy fallback:
    #: attempt to sign and let the server surface any mismatch).
    signing_key_fingerprint: str | None = None
    #: Long-lived member API key written by ``alter login``. This is the
    #: credential the bridge sends as ``X-ALTER-API-Key`` for member-self tools
    #: (doctrine, messaging, alignment, consent, attunement) - those tools
    #: require ``member_self`` scope, which the 24h bearer JWT does NOT carry.
    #: The doctrine-projection poller authenticates with this key; ``None`` when
    #: the session predates the member-key cutover (the poller then soft-fails
    #: the doctrine read and logs, never crashes).
    member_api_key: str | None = None
    #: The member's UUID (assessment-DB ``members.id``). Carried for parity with
    #: the bridge; the backend resolves ownership from the validated credential,
    #: not from this value. ``None`` on legacy sessions.
    member_id: str | None = None


class SessionRef:
    """Mutable holder for the live :class:`Session`.

    Subscribers that need a fresh JWT after a proactive refresh read
    ``.current.jwt`` through this holder instead of holding a frozen
    :class:`Session` snapshot.  When the :class:`SessionRefresher` rotates the
    token on disk it calls :meth:`set` once; every subsequent ``.current``
    read gets the updated JWT with zero additional coupling between
    components.

    Thread safety
    -------------
    No lock is needed.  The daemon runs a single-threaded asyncio event loop
    where coroutine scheduling is cooperative, so all reads and the single
    write are serialised by the loop (same justification as
    ``DaemonCapCache``'s plain-dict stores).
    """

    __slots__ = ("_session",)

    def __init__(self, session: Session) -> None:
        self._session: Session = session

    @property
    def current(self) -> Session:
        """Return the most-recently loaded :class:`Session`."""
        return self._session

    def set(self, session: Session) -> None:
        """Replace the held session (called by :class:`SessionRefresher`)."""
        self._session = session

    def reload(self) -> Session | None:
        """Re-read the session from disk and update the holder if valid.

        Returns the new :class:`Session` on success, ``None`` if
        :func:`load_session` returns nothing (e.g. the file disappeared).
        The holder is only updated on a valid reload.
        """
        fresh = load_session()
        if fresh is not None:
            self._session = fresh
        return fresh


def session_path() -> Path:
    """Path to the CLI's legacy plaintext session.json.

    Kept for the legacy-fallback read and the ``ALTER_SESSION_FILE``
    override. The CLI's encrypted-session cutover deletes this file after
    migrating the session into the secure store - see
    :func:`load_session` for the full resolution order.
    """
    override = os.environ.get("ALTER_SESSION_FILE")
    if override:
        return Path(override).expanduser()
    return config_dir() / "session.json"


def enc_session_path() -> Path:
    """Path to the CLI's encrypted-file-backend session blob.

    Written by the CLI's secure store when no
    OS-native credential tool is available (or when
    ``ALTER_SECURE_STORE_BACKEND=file`` forces the file backend). Blob
    layout: ``[12-byte IV][16-byte GCM tag][AES-256-GCM ciphertext]``.
    """
    return config_dir() / "enc" / "session.bin"


def enc_keyfile_path() -> Path:
    """Path to the 32-byte raw AES-256 key for the encrypted-file backend.

    Mirrors the CLI's active-keyfile resolution. The key and the
    ciphertext are separate files so reading either in isolation yields
    nothing; there is no device binding (documented CLI trade-off).
    """
    return config_dir() / "enc-keyfile"


# ---------------------------------------------------------------------------
# Secure-store read surface (read-only mirror of the CLI's contract)
# ---------------------------------------------------------------------------
#
# The CLI's secure store selects ONE
# backend at runtime: DPAPI (win32), macOS Keychain (darwin), libsecret
# (linux), or the AES-256-GCM encrypted-file fallback. The daemon cannot
# safely replicate the CLI's *probe-then-pick* selection - a systemd user
# service probes a different environment than the interactive shell that ran
# ``alter login`` (e.g. D-Bus session bus present in one, absent in the
# other). Instead the daemon tries each read surface in a deterministic
# order and accepts the first VALID session; the surfaces are mutually
# exclusive in practice (the CLI writes to exactly one), so first-hit-wins
# is unambiguous.
#
# Every read here is strictly read-only: no writes, no migration, no
# deletion. The OS-tool invocations are the same stable public CLI
# contracts (`secret-tool lookup`, `security find-generic-password`) that
# the CLI itself shells out to - the one place the daemon must implement
# crypto itself is the encrypted-file fallback, whose 3-field blob layout
# is the CLI's documented on-disk format (and which `cryptography`, already
# a base dependency for Ed25519 frame verification, decrypts natively).

#: Service / account keys used by the CLI's secure store. Must match
#: the CLI's secure-store service and session-store account names.
SECURE_STORE_SERVICE: str = "alter-cli"
SECURE_STORE_SESSION_ACCOUNT: str = "session"
SECURE_STORE_SIGNING_KEY_ACCOUNT: str = "signing-key"

#: Timeout for OS credential-tool shell-outs. Matches the CLI's own 10s
#: execFileSync budget - a locked keyring / frozen D-Bus must not wedge
#: daemon startup.
_OS_STORE_TIMEOUT_SECONDS: float = 10.0


def read_os_secret_store(account: str = SECURE_STORE_SESSION_ACCOUNT) -> str | None:
    """Read a named account from the platform's native credential store.

    Returns the raw secret string, or ``None`` when the tool is absent,
    the item is missing, the call times out, or the platform has no
    supported native read (win32 - the daemon's Windows surface is not yet
    supported; DPAPI read is deferred. The enc-file and legacy fallbacks
    still apply there). Never raises.

    Parameters
    ----------
    account:
        The account name within the ``alter-cli`` service namespace.
        Defaults to ``"session"``; pass ``"signing-key"`` to read the
        ES256 private-key envelope written by ``alter login`` (current
        login format, a JSON envelope ``{v,kid,private_key_pem,
        public_key_fingerprint}``; legacy stores a bare PKCS8 PEM).
    """
    try:
        if sys.platform.startswith("linux"):
            # Mirror the CLI's libsecret probe: without a session D-Bus the
            # lookup would hit the system bus or hang - skip outright.
            if not os.environ.get("DBUS_SESSION_BUS_ADDRESS"):
                return None
            if shutil.which("secret-tool") is None:
                return None
            result = subprocess.run(
                [
                    "secret-tool",
                    "lookup",
                    "service",
                    SECURE_STORE_SERVICE,
                    "account",
                    account,
                ],
                capture_output=True,
                text=True,
                timeout=_OS_STORE_TIMEOUT_SECONDS,
                check=False,
            )
            if result.returncode != 0 or not result.stdout:
                return None
            return result.stdout
        if sys.platform == "darwin":
            if not Path("/usr/bin/security").exists():
                return None
            result = subprocess.run(
                [
                    "/usr/bin/security",
                    "find-generic-password",
                    "-s",
                    SECURE_STORE_SERVICE,
                    "-a",
                    account,
                    "-w",
                ],
                capture_output=True,
                text=True,
                timeout=_OS_STORE_TIMEOUT_SECONDS,
                check=False,
            )
            if result.returncode != 0 or not result.stdout:
                return None
            return result.stdout
    except (OSError, subprocess.TimeoutExpired, subprocess.SubprocessError):
        return None
    return None


def _read_os_secret_store() -> str | None:
    """Read the session blob from the platform's native credential store.

    Thin wrapper over :func:`read_os_secret_store` that preserves the
    pre-generalisation call signature used by :func:`load_session`.
    """
    return read_os_secret_store(SECURE_STORE_SESSION_ACCOUNT)


def read_enc_store(enc_filename: str = "session.bin") -> str | None:
    """Decrypt a named blob from the CLI's encrypted-file backend.

    Format per the CLI's encrypted-file backend:
    ``enc/<enc_filename>`` = ``[12-byte IV][16-byte auth tag][ciphertext]``,
    AES-256-GCM with the 32-byte raw key at ``enc-keyfile``. Returns the
    decrypted UTF-8 string or ``None`` on any failure (missing files,
    truncated blob, wrong-size key, bad tag). Never raises.

    Parameters
    ----------
    enc_filename:
        Filename (NOT a path) within ``~/.config/alter/enc/``. Defaults
        to ``"session.bin"`` (the session blob). Pass ``"signing-key.bin"``
        to read the ES256 private-key envelope (same blob layout, same
        keyfile).
    """
    try:
        blob = (config_dir() / "enc" / enc_filename).read_bytes()
        key = enc_keyfile_path().read_bytes()
    except OSError:
        return None
    if len(blob) < 28 or len(key) != 32:
        # 12-byte IV + 16-byte tag minimum; key must be exactly AES-256.
        return None
    # Imported lazily to keep module import cheap; `cryptography` is already
    # a base dependency (Ed25519 frame-signature verification).
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    iv = blob[:12]
    tag = blob[12:28]
    ciphertext = blob[28:]
    try:
        # AESGCM.decrypt expects ciphertext||tag; the CLI stores the tag
        # BEFORE the ciphertext, so reorder here.
        plaintext = AESGCM(key).decrypt(iv, ciphertext + tag, None)
    except Exception:
        # InvalidTag / malformed input - corrupt blob or rotated keyfile.
        return None
    try:
        return plaintext.decode("utf-8")
    except UnicodeDecodeError:
        return None


def _read_enc_store() -> str | None:
    """Decrypt the CLI's encrypted-file-backend session blob.

    Thin wrapper over :func:`read_enc_store` that preserves the
    pre-generalisation call signature used by :func:`load_session`.
    """
    return read_enc_store("session.bin")


def _parse_consent_tier(value: Any) -> int:
    """Normalise ``consent_tier`` to the integer ~alter uses internally.

    The CLI writes the consent tier as a string label
    (``"L1"``, ``"L2"``, ``"L3"``, ``"L4"``) - see the SDK type
    definitions and the canonical session.json
    written by ``alter login``. The Python runtime stores it as the numeric
    tier. Accept both shapes plus the fallback default so a hand-edited
    session file cannot brick the daemon.
    """
    if isinstance(value, bool):
        # bool is a subclass of int - reject it explicitly to avoid
        # True → 1 sneak-through from a typo in session.json.
        return 1
    if isinstance(value, int):
        if 1 <= value <= 4:
            return value
        return 1
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return 1
        # "L1".."L4" → 1..4
        if len(stripped) == 2 and stripped[0] in ("L", "l") and stripped[1].isdigit():
            tier = int(stripped[1])
            if 1 <= tier <= 4:
                return tier
        # Raw numeric strings "1".."4" as a last resort.
        try:
            tier = int(stripped)
        except ValueError:
            return 1
        if 1 <= tier <= 4:
            return tier
    return 1


def _parse_session_text(raw_text: str) -> Session | None:
    """Parse + validate raw session JSON from any store backend.

    Shared by every read surface (OS store, enc-file, legacy plaintext) so
    the schema validation and the https gate apply uniformly
    regardless of where the bytes came from.
    """
    try:
        raw = json.loads(raw_text)
    except (json.JSONDecodeError, ValueError):
        return None
    if not isinstance(raw, dict):
        return None
    try:
        session = Session(
            handle=raw["handle"],
            api=raw.get("api", "https://api.truealter.com"),
            jwt=raw["jwt"],
            jwt_expires_at=raw["jwt_expires_at"],
            consent_tier=_parse_consent_tier(raw.get("consent_tier", 1)),
            user_id=raw.get("user_id", ""),
            email=raw.get("email", ""),
            orgs=list(raw.get("orgs", [])),
            id_token=raw.get("id_token"),
            refresh_token=raw.get("refresh_token"),
            refresh_expires_at=raw.get("refresh_expires_at"),
            logged_in_at=raw.get("logged_in_at"),
            signing_kid=raw.get("signing_kid") or None,
            signing_key_fingerprint=raw.get("signing_key_fingerprint") or None,
            member_api_key=raw.get("member_api_key") or None,
            member_id=raw.get("member_id") or None,
        )
    except (KeyError, TypeError):
        return None
    # reject http:// api endpoints - the subscriber
    # POSTs session.jwt as a Bearer token; plaintext delivery is not acceptable.
    try:
        _require_https("session.api", session.api)
    except ConfigError:
        return None
    return session


def _load_session_file(path: Path) -> Session | None:
    """Read + parse a plaintext session JSON file. ``None`` if absent/invalid."""
    if not path.exists():
        return None
    try:
        raw_text = path.read_text()
    except OSError:
        return None
    return _parse_session_text(raw_text)


def load_session() -> Session | None:
    """Load the CLI session, returning ``None`` if absent/invalid.

    Resolution order (first VALID session wins):

    1. ``ALTER_SESSION_FILE`` env override - an explicit plaintext JSON
       path pinned by the operator or the test suite. When set, no other
       surface is probed (the override is a redirect, not a preference).
    2. The OS-native credential store, via the same read contract
       the CLI uses (``secret-tool lookup`` on Linux,
       ``security find-generic-password`` on macOS). Skipped when
       ``ALTER_SECURE_STORE_BACKEND=file`` forces the file backend -
       mirroring the CLI's own env override.
    3. The encrypted-file fallback at
       ``$XDG_CONFIG_HOME/alter/enc/session.bin`` (AES-256-GCM, keyed by
       ``enc-keyfile``) - the backend the CLI selects on hosts without a
       reachable OS keyring.
    4. The legacy plaintext ``$XDG_CONFIG_HOME/alter/session.json``
       (pre-cutover installs; the CLI deletes it after migration).

    The daemon treats an absent session as "not yet logged in" and continues
    running in degraded mode (can still ingest signals once the user runs
    `alter login`).
    """
    # 1. Explicit override - honour it exclusively, preserving the
    #    pre-cutover behaviour where a pinned-but-missing file means
    #    "no session" rather than silently falling back to ~/.config.
    override = os.environ.get("ALTER_SESSION_FILE")
    if override:
        return _load_session_file(Path(override).expanduser())

    # 2. OS-native secure store (read-only, same contract as the CLI).
    if os.environ.get("ALTER_SECURE_STORE_BACKEND") != "file":
        raw_text = _read_os_secret_store()
        if raw_text is not None:
            session = _parse_session_text(raw_text)
            if session is not None:
                return session

    # 3. Encrypted-file fallback (enc/session.bin + enc-keyfile).
    raw_text = _read_enc_store()
    if raw_text is not None:
        session = _parse_session_text(raw_text)
        if session is not None:
            return session

    # 4. Legacy plaintext session.json.
    return _load_session_file(session_path())


# ---------------------------------------------------------------------------
# Daemon configuration
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Endpoint hardening
# ---------------------------------------------------------------------------
#
# The daemon accepts IdentityEvent frames from its SSE subscriber and
# projects them into ~/.cache/alter/identity.json and the inbox. Until full
# Ed25519 frame-signature verification is enabled end to end, this module
# applies a small set of load-time guards:
#
#   1.  ``http://`` endpoints are rejected with a loud error at load - TLS is
#       not optional.
#   2.  The ``runtime.yaml`` endpoint override (which previously let any local
#       process swap the DO/MCP endpoint to an attacker-controlled URL) is
#       gated behind ``ALTER_RUNTIME_DEV=1``.
#   3.  A ``require_frame_signature`` flag turns on per-frame Ed25519
#       verification once a pinned public key is configured.


class ConfigError(RuntimeError):
    """Raised when the loaded configuration fails a hardening invariant.

    Never swallowed - if the daemon is misconfigured in a way that would
    weaken the prompt-injection chain, we refuse to start. Louder than a log
    line at this stage of the lifecycle.
    """


def _require_https(name: str, value: str) -> None:
    """Reject any non-``https://`` endpoint at config load."""
    if not isinstance(value, str) or not value:
        raise ConfigError(f"{name} must be a non-empty https:// URL (got {value!r})")
    # Normalise only for validation; the original string is kept for the
    # httpx client so any path templating (``{handle}``) still works.
    lowered = value.lower()
    if lowered.startswith("http://"):
        raise ConfigError(
            f"{name}={value!r} uses http:// - TLS is mandatory. "
            "Set the endpoint to an https:// URL or leave the default."
        )
    if not lowered.startswith("https://"):
        raise ConfigError(
            f"{name}={value!r} is not an https:// URL - only https:// endpoints are accepted."
        )


#: Matches a legacy host segment so the normaliser in
#: :meth:`DaemonConfig.load` can rewrite it to the current default host.
_LEGACY_HOST_RE = re.compile(r"-staging(?=\.truealter\.com)")


def _heal_staging_host(value: str) -> str | None:
    """Return *value* with a legacy host segment rewritten to the current
    default host, or ``None`` if no such host is present.

    Only the host segment is substituted; scheme and any path templating
    (``{handle}``) are preserved. A current-default URL never spuriously
    matches, so calling this on an already-current endpoint is a no-op.
    """
    if not isinstance(value, str):
        return None
    if _LEGACY_HOST_RE.search(value) is None:
        return None
    return _LEGACY_HOST_RE.sub("", value)


@dataclass
class DaemonConfig:
    """Runtime daemon configuration.

    Defaults target the hosted identity-event endpoint and the MCP
    fallback endpoint.
    """

    # Primary - per-handle DO SSE endpoint template (handle is substituted at runtime)
    do_sse_endpoint: str = "https://mcp.truealter.com/events/{handle}/stream"
    do_state_endpoint: str = "https://mcp.truealter.com/events/{handle}/state"
    do_ingest_endpoint: str = "https://mcp.truealter.com/events/{handle}/ingest"

    # Fallback - direct MCP polling.
    #
    # ``fallback_trigger_after_seconds`` doubles as the SSE chunk read timeout
    # in :class:`DoSseSubscriber._consume_stream`. The server
    # emits SSE keepalive comments every 25s
    # (the server-side keepalive interval),
    # so this value MUST exceed the keepalive interval - otherwise the stall
    # watchdog fires before any keepalive arrives, every connection is treated
    # as stalled, and the daemon enters a tight reconnect loop (~4s/cycle =
    # ~21,600 reconnects/day per handle, observed 2026-04-29 as 139k/day across
    # two handles). 75s = 3× keepalive, absorbing one missed ping plus
    # clock skew. If the SSE_PING_INTERVAL_MS server constant is changed,
    # this floor must be re-derived.
    mcp_fallback_endpoint: str = "https://api.truealter.com/api/v1/mcp"
    fallback_poll_interval_seconds: float = 30.0
    fallback_trigger_after_seconds: float = 75.0

    # --- Attunement refresher (always-on, independent of DO connection) ---
    #: Master toggle for :class:`AttunementRefresher`. The MCP fallback poller
    #: only carries attunement to the cache while the DO SSE feed is *down*; in
    #: normal operation the DO stays connected and the fallback is idle, so the
    #: attunement score in ``~/.cache/alter/identity.json`` never refreshes.
    #: This component closes that gap: it calls the ``alter_attunement`` MCP
    #: tool on a slow cadence *regardless* of DO connection state and projects
    #: the result through the cache writer. Disable via
    #: ``ALTER_RUNTIME_ATTUNEMENT_REFRESH=0`` (e.g. air-gapped fleets that
    #: don't want the periodic authenticated round-trip).
    attunement_refresh_enabled: bool = True
    #: Cadence in seconds for the attunement refresh poll. 300s (5 min) is
    #: deliberately slow: attunement is a low-velocity signal and the goal is
    #: a steadily-fresh cache, not a tight feedback loop. Independent of
    #: ``fallback_poll_interval_seconds`` (the fallback is a fast crisis-mode
    #: poller; this is a low-frequency maintenance refresh). Override via
    #: ``ALTER_RUNTIME_ATTUNEMENT_REFRESH_INTERVAL_SECONDS``.
    attunement_refresh_interval_seconds: float = 300.0

    # --- Proactive session refresher ------------------------------------------
    #: Master toggle for :class:`SessionRefresher`. When enabled (the default)
    #: the daemon shells ``alter creds refresh --force`` a configurable lead
    #: time before the access JWT expires, so subscribers never hit the 6-hour
    #: 401-spiral boundary. Disable via ``ALTER_RUNTIME_SESSION_REFRESH=0``
    #: (e.g. CI environments where the CLI binary is absent).
    session_refresh_enabled: bool = True
    #: Seconds before JWT expiry at which the refresher wakes and attempts a
    #: rotation.  300 s (5 min) gives enough runway to complete the subprocess
    #: and propagate the new token to all holders before any subscriber fires
    #: an authenticated request with the old JWT.  Override via
    #: ``ALTER_RUNTIME_SESSION_REFRESH_LEAD_SECONDS``.
    session_refresh_lead_seconds: float = 300.0
    #: ``asyncio.wait_for`` timeout for the ``alter creds refresh --force``
    #: subprocess in seconds.  40 s is generous for the OAuth round-trip; on
    #: timeout the subprocess is killed and the next wake retries with backoff.
    #: Override via ``ALTER_RUNTIME_SESSION_REFRESH_SUBPROCESS_TIMEOUT_SECONDS``.
    session_refresh_subprocess_timeout_seconds: float = 40.0

    # Cross-host session presence (session_presence intent + /queries/presence
    # projection). The daemon polls on a cadence and writes a sessions.json
    # cache file that external session-awareness tooling reads. The capability
    # request carries the alter_org.read scope on each cycle.
    org_alter_caps_endpoint: str = "https://api.truealter.com/api/v1/org-alter/caps"
    org_alter_presence_endpoint: str = "https://mcp.truealter.com/orgs/alter/queries/presence"
    session_presence_enabled: bool = True
    session_presence_poll_interval_seconds: float = 30.0

    # --- Active-sessions DO publisher ------------------------------------
    #: Base URL for the per-``~handle`` Cloudflare Durable Object. The publisher
    #: POSTs each new envelope to
    #: ``{do_publish_url}/events/{handle}/sessions/ingest`` where
    #: ``{handle}`` is read from the envelope payload. Trailing slashes are
    #: stripped. Override via ``ALTER_RUNTIME_DO_PUBLISH_URL``.
    do_publish_url: str = "https://mcp.truealter.com"
    #: When ``True``, register :class:`ActiveSessionsDoPublisher` as a
    #: supervised Component. Default ``True`` so the daemon ships the wire
    #: publishing on by default; disable via
    #: ``ALTER_RUNTIME_DO_PUBLISH_ENABLED=0`` on hosts that intentionally
    #: run local-only. The publisher mints a cap-JWT scoped
    #: ``alter_events.sessions.ingest`` via the backend capability request endpoint
    #: using the CLI session.jwt - no static service-token env
    #: variable; the credential follows the live session.
    do_publish_enabled: bool = True
    #: Tick interval for the publisher's tail loop. 30 s keeps cross-host
    #: visibility lag bounded (one tick + one DO round-trip) while cutting the
    #: idle DO write/poll volume ~6x versus the old 5 s cadence; the 5 s tick
    #: was a dev-harness amplifier, not a product requirement. Override via
    #: ``ALTER_RUNTIME_DO_PUBLISH_POLL_INTERVAL_SECONDS``.
    do_publish_poll_interval_seconds: float = 30.0

    # --- Active-sessions GC pass ------------------------------------------
    #: Master toggle for the periodic GC sweep over the active-sessions
    #: JSONL. When disabled the daemon never emits idle/terminated
    #: transitions on its own - relies solely on tool-side
    #: ``session_ended`` emissions.
    active_sessions_gc_enabled: bool = True
    #: Cadence of the GC tick. 60s is well below the default idle
    #: threshold so a session moves from ``active`` to ``idle`` within
    #: roughly one tick of crossing the boundary.
    active_sessions_gc_interval_seconds: float = 60.0
    #: A session whose ``last_activity`` is older than this is folded
    #: from ``active`` to ``idle``. 5 minutes matches the existing
    #: heartbeat cadence ceiling.
    active_sessions_idle_after_seconds: float = 300.0
    #: A session whose ``last_activity`` is older than this is folded
    #: to ``complete``. For ``tool == "cc"`` the PID is additionally
    #: probed via ``os.kill(pid, 0)`` - only dead PIDs are reaped.
    active_sessions_terminated_after_seconds: float = 900.0

    # --- Presence feed writer (CLI ``alter room`` presence pane) ---------
    #: When ``True``, register :class:`PresenceFeedWriter` as a supervised
    #: Component. The writer subscribes to ``identity.event`` presence_set
    #: frames from granted peers and projects the CLI-shaped subset
    #: (``sender``/``state``/``sent_at``/``until``) into
    #: ``~/.local/share/alter-runtime/presence-feed.jsonl`` - the file the
    #: the ``alter room`` CLI pane reads. Default ``True`` so presence
    #: works out of the box; disable via
    #: ``ALTER_RUNTIME_PRESENCE_FEED_WRITER=0`` on hosts that intentionally
    #: run without the room pane.
    presence_feed_writer_enabled: bool = True

    #: Desktop notifier. Renders a freedesktop toast (notify-send + system
    #: message chime) on each inbound ``alter_message`` addressed to the local
    #: handle. This is the arrival cue that makes peer messages feel native
    #: rather than something you have to remember to poll. Default ``True``;
    #: disable via ``ALTER_DESKTOP_NOTIFIER_DISABLED=1`` (the var the notifier
    #: advertises in its own cold-fail warning).
    desktop_notifier_enabled: bool = True

    # Socket server
    unix_socket: Path = field(default_factory=unix_socket_path)
    enable_dbus: bool = sys.platform.startswith("linux")

    # Cache
    cache_ttl_seconds: int = 300  # matches the shell integration cache TTL

    # Telemetry
    log_level: str = "INFO"

    # --- Claude Code JSONL token-usage watcher ---------------------------
    #: When ``True``, register :class:`ClaudeJsonlWatcher` as a supervised
    #: Component. Opt-in (default ``False``) because not every principal's
    #: machine needs ops token-usage telemetry, and the watcher requires a
    #: valid session JWT to POST events to the backend. Enable via env var
    #: ``ALTER_RUNTIME_CLAUDE_JSONL_WATCHER=1`` or direct config mutation.
    enable_claude_jsonl_watcher: bool = False

    # --- Hardening (frame-signature enforcement) --------------
    #: When ``True``, every SSE frame received by :class:`DoSseSubscriber`
    #: MUST carry a valid Ed25519 signature over the canonical (JCS-style
    #: stable-key-sorted) JSON bytes of the payload with the ``signature``
    #: field removed. Frames that are unsigned, carry a malformed signature,
    #: declare a ``pubkey`` that differs from the pinned
    #: :attr:`frame_signature_pubkey`, or fail Ed25519 verification are
    #: dropped with a structured warning log; counters on the subscriber's
    #: :class:`_ConnectionState` record each drop class.
    #:
    #: Default is ``True`` post-pentest 2026-04-26 - operators must now
    #: deliberately disable enforcement (``ALTER_RUNTIME_REQUIRE_FRAME_SIG=0``)
    #: rather than silently inheriting the migration-window pass-through. The
    #: subscriber refuses to construct when enforcement is on without a pinned
    #: pubkey (see the startup guard in ``do_sse.py``), so flipping the default
    #: to ``True`` forces operators to either provide
    #: ``ALTER_RUNTIME_FRAME_SIG_PUBKEY`` or explicitly opt out - preferable
    #: to the previous failure mode where unsigned frames were accepted by
    #: default if the operator forgot to flip the flag at deploy time.
    #:
    #: Disable via ``ALTER_RUNTIME_REQUIRE_FRAME_SIG=0`` (only valid during
    #: the DO-side signer migration window).
    require_frame_signature: bool = True

    #: Pinned Ed25519 public key for the DO emitting the SSE
    #: stream. Expected format: ``ed25519:<base64url>`` matching the
    #: canonical-fragment envelope convention. When
    #: :attr:`require_frame_signature` is ``True`` this MUST be set - the
    #: subscriber refuses to construct otherwise (see the startup guard)
    #: to prevent self-certifying-frame attacks where a frame's
    #: declared pubkey is trusted solely on its own authority.
    #:
    #: Override via ``ALTER_RUNTIME_FRAME_SIG_PUBKEY``.
    #:
    #: Follow-up: the durable source of truth is the DO's ``/state``
    #: endpoint (returns the current envelope with epoch-rotating pubkey);
    #: a future PR fetches it on subscriber start-up and pins dynamically.
    #: Static env-var pin is the interim trust root.
    frame_signature_pubkey: str | None = None

    # --- Daemon update loop -----------------------------------------------
    #: Master toggle for the auto-update poll loop. Default ``True``: the
    #: install-once posture means the daemon keeps itself aware of newer
    #: releases. Operators flip to ``False`` (``ALTER_RUNTIME_AUTOUPDATE=0``)
    #: when they want zero outbound polling, e.g. air-gapped fleets or
    #: integration tests that don't want a phantom network call.
    #:
    #: The loop only polls and logs; download, signature verification, and
    #: atomic-replace are handled by a separate update path. Disabling saves
    #: a periodic HTTPS round-trip to releases.truealter.com.
    autoupdate_enabled: bool = True
    #: Override the manifest URL. Defaults to the production release host.
    #: Override via ``ALTER_RUNTIME_AUTOUPDATE_MANIFEST_URL`` (for example to
    #: point integration tests at a non-production manifest).
    autoupdate_manifest_url: str = "https://releases.truealter.com/manifest.json"
    #: Poll cadence in seconds. 24h (every-UTC-midnight ± jitter).
    #: Lower in dev to exercise the loop quickly. Override via
    #: ``ALTER_RUNTIME_AUTOUPDATE_POLL_INTERVAL_SECONDS``.
    autoupdate_poll_interval_seconds: int = 24 * 60 * 60

    # --- Doctrine projection poller --------------------------------------
    #: Master toggle for :class:`DoctrineProjectionPoller`. When enabled (the
    #: default) the daemon maintains a local read-only JSONL projection of the
    #: member's doctrine substrate per scope (``personal`` / ``collective``)
    #: under :func:`doctrine_projection_dir`. Pull-mode (the backend emits no
    #: event on a doctrine write): the poller calls ``alter_doctrine``'s cheap
    #: ``summary`` verb each tick and only pulls the ``list`` delta when the
    #: etag changes. It shares the read-side MCP wire contract (envelope +
    #: ``mcp_fallback_endpoint`` + Bearer JWT) with the other pollers. Disable
    #: via ``ALTER_RUNTIME_DOCTRINE_PROJECTION=0`` (e.g. air-gapped fleets that
    #: don't want the periodic authenticated round-trip).
    doctrine_projection_enabled: bool = True
    #: Cadence in seconds for the doctrine summary poll. 60s is deliberately
    #: slow: doctrine is a low-velocity living-state surface and the summary
    #: call is cheap, so a steadily-fresh cache (not a tight loop) is the goal.
    #: Override via ``ALTER_RUNTIME_DOCTRINE_PROJECTION_INTERVAL_SECONDS``.
    doctrine_projection_interval_seconds: float = 60.0

    # --- Loom verdict cross-machine feed (read-only foundation) ----------
    # Two independent components share this config block: the desktop
    # LoomVerdictExporter (producer side) and the thin-client
    # LoomVerdictSubscriber (read-only mirror side). A single host may run
    # either, both, or neither depending on whether it IS the loom
    # validator or merely reads a served verdict.
    #: Master toggle for :class:`LoomVerdictExporter`. Default ``False``:
    #: only the single machine acting as the loom validator should ever
    #: tail its local verdict store and re-emit rows cross-machine. A thin
    #: client has no validator verdicts to export; enabling this there is
    #: a harmless no-op (the poll finds nothing matching the ``loom:``
    #: concern prefix) but the default stays off so the capability is
    #: opt-in per the single-producer-of-record posture. Enable via
    #: ``ALTER_RUNTIME_LOOM_VERDICT_EXPORTER=1`` on the validator host only.
    loom_verdict_exporter_enabled: bool = False
    #: Poll interval for the exporter's verdict-store tail. A portable
    #: poll-based tail (no inotify/watchdog dependency) so Windows, macOS,
    #: and Linux behave identically - the verdict store is written
    #: relatively infrequently (once per Loom-validate run), so a few
    #: seconds of latency is an acceptable trade for portability. Override
    #: via ``ALTER_RUNTIME_LOOM_VERDICT_EXPORTER_POLL_INTERVAL_SECONDS``.
    loom_verdict_exporter_poll_interval_seconds: float = 5.0
    #: Backend REST endpoint the exporter POSTs the strict 4-field
    #: allowlist payload to (``POST .../identity-events/loom-verdict``).
    #: Override via ``ALTER_RUNTIME_LOOM_VERDICT_ENDPOINT``.
    loom_verdict_endpoint: str = "https://api.truealter.com/api/v1/identity-events/loom-verdict"

    #: Master toggle for :class:`LoomVerdictSubscriber` (thin-client
    #: read-only mirror). Default ``True``, mirroring
    #: :class:`~alter_runtime.subscribers.agent_frames.AgentFrameSubscriber`'s
    #: always-on posture: it is read-only, cheap (filters the existing
    #: DO-SSE bus stream), and safe on every host including the validator's
    #: own desktop. Disable via ``ALTER_RUNTIME_LOOM_VERDICT_SUBSCRIBER=0``.
    loom_verdict_subscriber_enabled: bool = True

    @classmethod
    def load(cls) -> DaemonConfig:
        """Load config from environment + YAML file + defaults.

        Raises
        ------
        ConfigError
            If any endpoint is non-``https://`` after env/YAML overrides,
            or if the YAML override is present without ``ALTER_RUNTIME_DEV=1``.
        """
        config = cls()
        # Endpoint fields pinned by an explicit ALTER_*_ENDPOINT env override.
        # The prod-default self-heal below leaves these alone so an
        # explicitly-configured endpoint is preserved as set.
        env_pinned_endpoints: set[str] = set()

        # Member-set behaviour toggles, applied BEFORE any env read so that an
        # explicit ALTER_* var still wins. Precedence stays env > file >
        # default, as the module docstring states.
        _apply_behaviour_toggles(config)

        # Environment overrides
        if endpoint := os.environ.get("ALTER_DO_SSE_ENDPOINT"):
            config.do_sse_endpoint = endpoint
            env_pinned_endpoints.add("do_sse_endpoint")
        if endpoint := os.environ.get("ALTER_DO_STATE_ENDPOINT"):
            config.do_state_endpoint = endpoint
            env_pinned_endpoints.add("do_state_endpoint")
        if endpoint := os.environ.get("ALTER_DO_INGEST_ENDPOINT"):
            config.do_ingest_endpoint = endpoint
            env_pinned_endpoints.add("do_ingest_endpoint")
        if endpoint := os.environ.get("ALTER_MCP_FALLBACK_ENDPOINT"):
            config.mcp_fallback_endpoint = endpoint
            env_pinned_endpoints.add("mcp_fallback_endpoint")
        if endpoint := os.environ.get("ALTER_ORG_ALTER_CAPS_ENDPOINT"):
            config.org_alter_caps_endpoint = endpoint
            env_pinned_endpoints.add("org_alter_caps_endpoint")
        if endpoint := os.environ.get("ALTER_ORG_ALTER_PRESENCE_ENDPOINT"):
            config.org_alter_presence_endpoint = endpoint
            env_pinned_endpoints.add("org_alter_presence_endpoint")
        _sp_flag = os.environ.get("ALTER_SESSION_PRESENCE_ENABLED", "").lower()
        if _sp_flag in ("0", "false", "no", "off"):
            config.session_presence_enabled = False
        elif _sp_flag in ("1", "true", "yes", "on"):
            config.session_presence_enabled = True
        if interval := os.environ.get("ALTER_SESSION_PRESENCE_POLL_INTERVAL_SECONDS"):
            try:
                config.session_presence_poll_interval_seconds = float(interval)
            except ValueError:
                pass  # Ignore malformed override; default stands.

        # --- Attunement refresher (always-on) ---------------------------
        _ar_flag = os.environ.get("ALTER_RUNTIME_ATTUNEMENT_REFRESH", "").lower()
        if _ar_flag in ("0", "false", "no", "off"):
            config.attunement_refresh_enabled = False
        elif _ar_flag in ("1", "true", "yes", "on"):
            config.attunement_refresh_enabled = True
        if ar_interval := os.environ.get("ALTER_RUNTIME_ATTUNEMENT_REFRESH_INTERVAL_SECONDS"):
            try:
                config.attunement_refresh_interval_seconds = float(ar_interval)
            except ValueError:
                pass  # Ignore malformed override; default stands.

        # --- Proactive session refresher --------------------------------
        _sr_flag = os.environ.get("ALTER_RUNTIME_SESSION_REFRESH", "").lower()
        if _sr_flag in ("0", "false", "no", "off"):
            config.session_refresh_enabled = False
        elif _sr_flag in ("1", "true", "yes", "on"):
            config.session_refresh_enabled = True
        if sr_lead := os.environ.get("ALTER_RUNTIME_SESSION_REFRESH_LEAD_SECONDS"):
            try:
                config.session_refresh_lead_seconds = float(sr_lead)
            except ValueError:
                pass  # Ignore malformed override; default stands.
        if sr_timeout := os.environ.get("ALTER_RUNTIME_SESSION_REFRESH_SUBPROCESS_TIMEOUT_SECONDS"):
            try:
                config.session_refresh_subprocess_timeout_seconds = float(sr_timeout)
            except ValueError:
                pass  # Ignore malformed override; default stands.

        # --- Active-sessions DO publisher --------------------------------
        if publish_url := os.environ.get("ALTER_RUNTIME_DO_PUBLISH_URL"):
            config.do_publish_url = publish_url
            env_pinned_endpoints.add("do_publish_url")
        _dpe_flag = os.environ.get("ALTER_RUNTIME_DO_PUBLISH_ENABLED", "").lower()
        if _dpe_flag in ("0", "false", "no", "off"):
            config.do_publish_enabled = False
        elif _dpe_flag in ("1", "true", "yes", "on"):
            config.do_publish_enabled = True
        if dpi := os.environ.get("ALTER_RUNTIME_DO_PUBLISH_POLL_INTERVAL_SECONDS"):
            try:
                config.do_publish_poll_interval_seconds = float(dpi)
            except ValueError:
                pass

        # --- Active-sessions GC pass ------------------------------------
        _gc_flag = os.environ.get("ALTER_ACTIVE_SESSIONS_GC_ENABLED", "").lower()
        if _gc_flag in ("0", "false", "no", "off"):
            config.active_sessions_gc_enabled = False
        elif _gc_flag in ("1", "true", "yes", "on"):
            config.active_sessions_gc_enabled = True
        if gc_interval := os.environ.get("ALTER_ACTIVE_SESSIONS_GC_INTERVAL_SECONDS"):
            try:
                config.active_sessions_gc_interval_seconds = float(gc_interval)
            except ValueError:
                pass  # Ignore malformed override; default stands.
        if idle_after := os.environ.get("ALTER_ACTIVE_SESSIONS_IDLE_AFTER_SECONDS"):
            try:
                config.active_sessions_idle_after_seconds = float(idle_after)
            except ValueError:
                pass
        if terminated_after := os.environ.get("ALTER_ACTIVE_SESSIONS_TERMINATED_AFTER_SECONDS"):
            try:
                config.active_sessions_terminated_after_seconds = float(terminated_after)
            except ValueError:
                pass

        # --- Presence feed writer (CLI ``alter room`` presence pane) -----
        _pfw_flag = os.environ.get("ALTER_RUNTIME_PRESENCE_FEED_WRITER", "").lower()
        if _pfw_flag in ("0", "false", "no", "off"):
            config.presence_feed_writer_enabled = False
        elif _pfw_flag in ("1", "true", "yes", "on"):
            config.presence_feed_writer_enabled = True

        # --- Desktop notifier (freedesktop toast on inbound message) -----
        # Advertised disable switch: ALTER_DESKTOP_NOTIFIER_DISABLED=1. The
        # var carries DISABLED semantics, so a truthy value turns the notifier
        # off; a falsey value force-enables (mirrors the other flag blocks).
        _dn_flag = os.environ.get("ALTER_DESKTOP_NOTIFIER_DISABLED", "").lower()
        if _dn_flag in ("1", "true", "yes", "on"):
            config.desktop_notifier_enabled = False
        elif _dn_flag in ("0", "false", "no", "off"):
            config.desktop_notifier_enabled = True

        # --- Daemon update loop ------------------------------------------
        _au_flag = os.environ.get("ALTER_RUNTIME_AUTOUPDATE", "").lower()
        if _au_flag in ("0", "false", "no", "off"):
            config.autoupdate_enabled = False
        elif _au_flag in ("1", "true", "yes", "on"):
            config.autoupdate_enabled = True
        if au_url := os.environ.get("ALTER_RUNTIME_AUTOUPDATE_MANIFEST_URL"):
            config.autoupdate_manifest_url = au_url
        if au_interval := os.environ.get("ALTER_RUNTIME_AUTOUPDATE_POLL_INTERVAL_SECONDS"):
            try:
                config.autoupdate_poll_interval_seconds = int(au_interval)
            except ValueError:
                pass

        # --- Doctrine projection poller ----------------------------------
        _dp_flag = os.environ.get("ALTER_RUNTIME_DOCTRINE_PROJECTION", "").lower()
        if _dp_flag in ("0", "false", "no", "off"):
            config.doctrine_projection_enabled = False
        elif _dp_flag in ("1", "true", "yes", "on"):
            config.doctrine_projection_enabled = True
        if dp_interval := os.environ.get("ALTER_RUNTIME_DOCTRINE_PROJECTION_INTERVAL_SECONDS"):
            try:
                config.doctrine_projection_interval_seconds = float(dp_interval)
            except ValueError:
                pass  # Ignore malformed override; default stands.

        # --- Loom verdict cross-machine feed -----------------------------
        _lve_flag = os.environ.get("ALTER_RUNTIME_LOOM_VERDICT_EXPORTER", "").lower()
        if _lve_flag in ("0", "false", "no", "off"):
            config.loom_verdict_exporter_enabled = False
        elif _lve_flag in ("1", "true", "yes", "on"):
            config.loom_verdict_exporter_enabled = True
        if lve_interval := os.environ.get(
            "ALTER_RUNTIME_LOOM_VERDICT_EXPORTER_POLL_INTERVAL_SECONDS"
        ):
            try:
                config.loom_verdict_exporter_poll_interval_seconds = float(lve_interval)
            except ValueError:
                pass  # Ignore malformed override; default stands.
        if lv_endpoint := os.environ.get("ALTER_RUNTIME_LOOM_VERDICT_ENDPOINT"):
            config.loom_verdict_endpoint = lv_endpoint
            env_pinned_endpoints.add("loom_verdict_endpoint")
        _lvs_flag = os.environ.get("ALTER_RUNTIME_LOOM_VERDICT_SUBSCRIBER", "").lower()
        if _lvs_flag in ("0", "false", "no", "off"):
            config.loom_verdict_subscriber_enabled = False
        elif _lvs_flag in ("1", "true", "yes", "on"):
            config.loom_verdict_subscriber_enabled = True

        if level := os.environ.get("ALTER_RUNTIME_LOG_LEVEL"):
            config.log_level = level
        if socket := os.environ.get("ALTER_RUNTIME_SOCKET"):
            config.unix_socket = Path(socket).expanduser()
        _cjw_flag = os.environ.get("ALTER_RUNTIME_CLAUDE_JSONL_WATCHER", "").lower()
        if _cjw_flag in ("1", "true", "yes", "on"):
            config.enable_claude_jsonl_watcher = True
        elif _cjw_flag in ("0", "false", "no", "off"):
            config.enable_claude_jsonl_watcher = False
        # Post-pentest-2026-04-26: default is True. Env var still toggles -
        # explicit "0"/"false"/"no"/"off" disables (migration-window opt-out),
        # everything else (including unset) keeps the default True.
        #
        # Production-lock: the opt-out is only
        # valid when ALTER_RUNTIME_DEV=1 is also set. In any non-dev
        # environment (ALTER_RUNTIME_DEV unset or not "1"/"true"/"yes") the
        # =0 value is silently overridden back to True and a structured
        # warning is emitted. This prevents a compromised or misconfigured
        # env from disabling frame-signature enforcement in production.
        _dev_mode = os.environ.get("ALTER_RUNTIME_DEV", "").lower() in (
            "1",
            "true",
            "yes",
        )
        _flag = os.environ.get("ALTER_RUNTIME_REQUIRE_FRAME_SIG", "").lower()
        if _flag in ("0", "false", "no", "off"):
            if _dev_mode:
                config.require_frame_signature = False
            else:
                # Production-lock: refuse the opt-out outside of dev mode.
                import logging as _logging

                _logging.getLogger(__name__).warning(
                    "ALTER_RUNTIME_REQUIRE_FRAME_SIG=0 ignored - opt-out is "
                    "only permitted when ALTER_RUNTIME_DEV=1 is set. "
                    "Frame-signature enforcement remains ENABLED. "
                    "If this is a migration-window deployment, set "
                    "ALTER_RUNTIME_DEV=1 explicitly."
                )
                config.require_frame_signature = True
        elif _flag in ("1", "true", "yes", "on"):
            config.require_frame_signature = True
        if pubkey := os.environ.get("ALTER_RUNTIME_FRAME_SIG_PUBKEY"):
            config.frame_signature_pubkey = pubkey

        # YAML file overrides - gated behind ALTER_RUNTIME_DEV=1.
        # Previously any local process could drop a runtime.yaml onto disk
        # and swap do_sse_endpoint to an attacker-controlled URL, which fed
        # unverified events into every connected client. The dev-only gate
        # closes that path for shipped builds until the Ed25519-signed config
        # file format lands.
        yaml_path = config_dir() / "runtime.yaml"
        if yaml_path.exists():
            dev_mode = os.environ.get("ALTER_RUNTIME_DEV", "").lower() in (
                "1",
                "true",
                "yes",
            )
            if not dev_mode:
                raise ConfigError(
                    f"{yaml_path} present but ALTER_RUNTIME_DEV is not set. "
                    "File-based endpoint overrides are dev-only - "
                    "remove the file, set endpoints via ALTER_*_ENDPOINT env "
                    "vars, or export ALTER_RUNTIME_DEV=1 explicitly."
                )
            try:
                import yaml  # imported lazily so tests without PyYAML still run

                with yaml_path.open("r") as f:
                    data = yaml.safe_load(f) or {}
                for key, value in data.items():
                    if hasattr(config, key):
                        setattr(config, key, value)
            except ImportError:
                # PyYAML not installed - surface loudly in dev mode so the
                # operator knows their override was ignored.
                raise
            except OSError:
                # Readable-but-broken YAML is swallowed (same as pre-harden
                # behaviour) - avoids a disk-error crash loop in dev.
                pass

        # --- Default-host normalisation ---------------------------------
        # Migrate any legacy host back to its current-default equivalent,
        # unless the operator pinned the endpoint with an explicit
        # ALTER_*_ENDPOINT env var. Runs after env + YAML overrides and
        # before the https invariants below.
        for _field in (
            "do_sse_endpoint",
            "do_state_endpoint",
            "do_ingest_endpoint",
            "mcp_fallback_endpoint",
            "org_alter_caps_endpoint",
            "org_alter_presence_endpoint",
            "do_publish_url",
        ):
            if _field in env_pinned_endpoints:
                continue
            _healed = _heal_staging_host(getattr(config, _field))
            if _healed is not None:
                import logging as _logging

                _logging.getLogger(__name__).warning(
                    "%s pointed at a non-production endpoint (%s); migrating to "
                    "production (%s). Set the matching ALTER_*_ENDPOINT env var "
                    "to override.",
                    _field,
                    getattr(config, _field),
                    _healed,
                )
                setattr(config, _field, _healed)

        # --- Post-override invariant checks -----------------------------
        _require_https("do_sse_endpoint", config.do_sse_endpoint)
        _require_https("do_state_endpoint", config.do_state_endpoint)
        _require_https("do_ingest_endpoint", config.do_ingest_endpoint)
        _require_https("mcp_fallback_endpoint", config.mcp_fallback_endpoint)
        _require_https("org_alter_caps_endpoint", config.org_alter_caps_endpoint)
        _require_https("org_alter_presence_endpoint", config.org_alter_presence_endpoint)
        _require_https("do_publish_url", config.do_publish_url)
        _require_https("loom_verdict_endpoint", config.loom_verdict_endpoint)

        return config


#: Behaviour fields a member may set from their own CLI, and nothing else.
#:
#: This allowlist is the whole security argument for reading the toggles file
#: ungated, next door to a ``runtime.yaml`` that refuses to load at all without
#: ``ALTER_RUNTIME_DEV=1``. That gate exists because runtime.yaml does a blind
#: ``setattr`` over every key it finds, so any local process could drop a file
#: on disk and repoint ``do_sse_endpoint`` at a host it controlled, feeding
#: unverified events to every connected client. The toggles file cannot do
#: that, and not by policy: an endpoint is a string, every name here maps to a
#: bool, and a value that is not exactly ``True`` or ``False`` is refused
#: below. The dangerous reach is absent by construction rather than forbidden
#: by a check someone can forget to keep.
#:
#: Adding a non-bool field here would silently re-open that path, so do not.
#: A new toggle is a new bool.
BEHAVIOUR_TOGGLE_FIELDS: frozenset[str] = frozenset(
    {
        "do_publish_enabled",
        "presence_feed_writer_enabled",
        "session_presence_enabled",
        "attunement_refresh_enabled",
        "desktop_notifier_enabled",
    }
)


def behaviour_toggles_path() -> Path:
    """Return the path of the member-set behaviour-toggle file."""
    return config_dir() / "daemon-toggles.json"


def _apply_behaviour_toggles(config: DaemonConfig) -> None:
    """Apply the member's own on/off choices over the built-in defaults.

    Every behaviour reachable from here is consent-bearing: whether this host
    announces its live sessions to peers, writes a presence feed, or raises a
    desktop notification. The member owns those answers, and until this file
    existed they could only be answered by exporting an environment variable
    into whatever launched the daemon, which is not an answer a person gives.

    Raises
    ------
    ConfigError
        If the file exists and cannot be read as the expected shape.

    A corrupt file is deliberately fatal rather than ignored, and the direction
    matters more than the strictness. Every default here is ON. Skipping a file
    we failed to parse would resolve each toggle back to ON, so a member who
    turned the session publisher OFF would have it turned silently back ON by a
    truncated write or a bad disk, and nothing would say so. The failure a
    person can see is a daemon that refuses to start; the failure they cannot
    see is the one that publishes their sessions after they asked it not to.
    Unreadable consent is not consent, so this declares and fails closed
    rather than decaying to a permissive default.

    An ABSENT file is not corruption and is the normal case: nobody has set a
    preference yet, the built-in defaults stand, and nothing is raised.
    """
    path = behaviour_toggles_path()
    try:
        raw = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return
    except OSError as exc:
        raise ConfigError(
            f"{path} exists but could not be read ({exc}). It records which "
            "daemon behaviours you turned off, and starting without it would "
            "silently turn them back on. Fix the file's permissions or remove "
            "it to accept the defaults."
        ) from exc

    try:
        data = json.loads(raw)
    except ValueError as exc:
        raise ConfigError(
            f"{path} is not valid JSON ({exc}). It records which daemon "
            "behaviours you turned off, and starting without it would silently "
            "turn them back on. Repair the file, or remove it to accept the "
            "defaults."
        ) from exc

    if not isinstance(data, dict):
        raise ConfigError(
            f"{path} must contain a JSON object mapping behaviour names to "
            f"true/false, found {type(data).__name__}."
        )

    for key, value in data.items():
        if key not in BEHAVIOUR_TOGGLE_FIELDS:
            # Forward and backward compatible: a newer CLI may write a toggle
            # this daemon has never heard of, and an older one may leave a
            # retired name behind. Neither is the member's problem, and neither
            # can reach a field, so both are skipped rather than raised.
            continue
        if not isinstance(value, bool):
            raise ConfigError(f"{path}: behaviour {key!r} must be true or false, found {value!r}.")
        setattr(config, key, value)


def load_config() -> DaemonConfig:
    """Public entrypoint - load daemon configuration."""
    return DaemonConfig.load()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def ensure_directories() -> None:
    """Create required XDG directories if they don't exist.

    Called by `alter-runtime init` and at daemon startup so that subsequent
    writes don't fail with FileNotFoundError.
    """
    for d in (config_dir(), cache_dir(), state_dir()):
        d.mkdir(parents=True, exist_ok=True, mode=0o700)
    socket_path = unix_socket_path()
    socket_path.parent.mkdir(parents=True, exist_ok=True)
